# Generated by Django 3.2.2 on 2021-05-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizadora',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_real', models.CharField(max_length=45)),
                ('nome_fantasia', models.CharField(max_length=45)),
            ],
        ),
    ]
